[sharedA]
description = "One of the five shared variables that you have access to."

[sharedB]
description = "One of the five shared variables that you have access to."

[sharedC]
description = "One of the five shared variables that you have access to."

[sharedD]
description = "One of the five shared variables that you have access to."

[sharedE]
description = "One of the five shared variables that you have access to."
